### ISSUE TITLE
Reproduction: Question about Model Weights

### ISSUE THREAD

**Issue by smdrnks** [Bitbol-Lab/ProtMamba-ssm#11]
Hi!

I just downloaded your model weights and I have a few questions. In the paper you train four different models:
- Protmamba Foundation
- Protmamba Foundation, FIM fine-tuned
- Protmamba Foundation Long
- Protmamba Foundation Long, FIM fine-tuned

My first question: Since there is only the Protmamba Foundation Long released, could you also consider releasing the weights for the remaining three models? At least the FiM tuned model would be great so I can reproduce the best Proteingym results from Figure 8.

Next I want to compare training curves. Does Figure 4 show the training of Foundation or Foundation Long?

Thanks again for your help!

**Comment by damiano-sg** [comment]
Hi @smdrnks I confirm that Fig 4 show the training of Foundation Long. The training curve of Foundation is the same (since it's the same model trained for less steps) but it stops at $6\times 10^{10}$ steps (i.e. when we increase the context size from $2^{15}$ to $2^{16}$ tokens).
