### ISSUE TITLE
mamba_ssm code version

### ISSUE THREAD

**Issue by aksangha** [Bitbol-Lab/ProtMamba-ssm#3]
Hi,

As the ProtMamba_ssm/ is missing the mamba_ssm code in the distribution, can you please point me to the right version of mamba_ssm code you used for ProtMamba or add that to the ProtMamba_ssm/? 

Thank you

**Comment by damiano-sg** [comment]
Hi, it's not missing, it's part of the `pip` requirements on `settings.ini`
It's the original mamba repository and it should be installed when you run `pip -e .`

**Comment by aksangha** [comment]
Thanks for the quick reply. 
Below is the first error I get from running ProtMamba. As you can see there is no layernorm function in mamba_ssm code, infact it is layer_norm. Next it errors with arguments on other mamba_ssm modules/functions. It seems that there are changes in the code that is being installed and that has been used.
Traceback (most recent call last):
  File "/home/ubuntu/scratch/ProtMamba-ssm/ProtMamba_ssm/sample_from_pretrained_model.py", line 4, in <module>
    from ProtMamba_ssm.modules import *
  File "/home/ubuntu/scratch/ProtMamba-ssm/ProtMamba_ssm/modules.py", line 19, in <module>
    from mamba_ssm.ops.triton.layernorm import RMSNorm, layer_norm_fn, rms_norm_fn
ModuleNotFoundError: No module named 'mamba_ssm.ops.triton.layernorm'

**Comment by damiano-sg** [comment]
Oh ok, we didn't specify the version on `setting.ini`, I'll fix it. A quick fix for you would be to downgrade Mamba to the version previous to Mamba2
