### ISSUE TITLE
Criteria to increase input length

### ISSUE THREAD

**Issue by sohviluukkonen** [Bitbol-Lab/ProtMamba-ssm#6]
Hi! In your paper shortly mention the procedure of increasing the sequence length once the loss plateaus:

> Initially, we used inputs of length L = 2^11 tokens with a batch size of 64. We doubled input length each time the loss reached a plateau, simultaneously reducing batch size to maintain a fixed total number of tokens per batch.

Unfortunately, I could not find either in the paper or the code, how do you define a plateau? Could you give me some information on this?

Thanks!

**Comment by damiano-sg** [comment]
Hi, that was defined empirically. We didn't follow a precise schedule for the input length.

**Comment by sohviluukkonen** [comment]
Thank you for your quick answer!
