### ISSUE TITLE
ColabFold MSA Reproduction for ProteinGym Benchmark

### ISSUE THREAD

**Issue by smdrnks** [Bitbol-Lab/ProtMamba-ssm#8]
Hi!

I am trying to reproduce the results for the ProteinGym benchmark. For that I need to create the target MSAs using ColabFold. Could you say a bit more about which settings were used for the ColabFold MSA generation? Your help would be greatly appreciated. Thank you!

**Comment by smdrnks** [comment]
Alternatively, would it be possible to provide the alignment files directly somehow?

**Comment by CyrilMa** [comment]
Hi @smdrnks,

Thank you for reaching out. 

You can get all alignments from [here](https://drive.google.com/drive/folders/1BBiBpXKHvKR6h-2MYegnbCB0zoSlo9ym?usp=sharing)

Alternatively, I added [here](https://github.com/Bitbol-Lab/ProtMamba-ssm/blob/proteingym_branch/tests/proteingym/mmseqs_search.py) the code that we used to make API calls to ColabFold (https://github.com/sokrypton/ColabFold/tree/main) adapted from their code

Keep in mind that it's their API so please cite them and adapt to their conditions :) 

> Is it okay to use the MMseqs2 MSA server (cf.run_mmseqs2) on a local computer?
> 
>     You can access the server from a local computer if you queries are serial from a single IP. Please do not use multiple computers to query the server.

Cyril

**Comment by smdrnks** [comment]
Hi Cyril.

Amazing! thanks a lot for providing the MSAs so fast. that's really helpful.
